<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>fr.master.representationconnaissances</groupId>
        <artifactId>rep-connais</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>reseaux_semantiques</artifactId>

    <dependencies>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <configuration>
                    <skip>false</skip>
                    <mainClass>fr.master.representationconnaissances.reseauxsemantiques.demo.DemonstrationReseauxSemantiques</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
